### ISSUE TITLE
Fail to remove a device with TestGUI_ZiGate_NXP-4

### ISSUE THREAD

**Issue by lboue** [fairecasoimeme/ZiGate#32] opened 2018-03-10 09:10 UTC
Hello,

I am trying to remove a device from the device list but I didn't succeed. I am getting an 'invalid parameter' error.  Zigate version: 3.0d
![zigate-remove-test](https://user-images.githubusercontent.com/938089/37240381-b41459c6-244a-11e8-97e8-1a69178c5359.png)

Here is my device list:
```
Type: 0x8015 (Get Devices List)
  Length: 4
  ID: 0
  Short Address: 0xB26C
  IEEE Address: 0x158D0001D5C468
  Power Source: 0
  Link Quality: 149
  ID: 1
  Short Address: 0x1BD7
  IEEE Address: 0x158D000123DE6E
  Power Source: 0
  Link Quality: 164
  ID: 2
  Short Address: 0x7629
  IEEE Address: 0x158D000170EB24
  Power Source: 0
  Link Quality: 195
  ID: 50
  Short Address: 0x6F44
  IEEE Address: 0xB57FFFE0D820A
  Power Source: 1
  Link Quality: 93
```
![zigate-device-list](https://user-images.githubusercontent.com/938089/37240404-03e2d162-244b-11e8-9f47-8c87e4b30324.png)

Somebody can help me please?

Regards,
Ludovic

**Comment by lboue** [comment] 2018-03-10 19:04
Actually I have to remove the '0x' prefix. So there is no more error from coming from TestGUI.
But this this error is from the zigate:
![zigate-remove-test2](https://user-images.githubusercontent.com/938089/37245790-ba2815fc-249d-11e8-8133-83dba93263c5.png)

```
Type: 0x8000 (Status)
  Length: 5
  Status: 0xA9 (ZigBee Error Code)
  SQN: 0x00
  Message: 
```

Is anyone managed to remove a device on the Zigate?
How can I do a Zigate reset factory?

Regards,
Ludovic

**Comment by doudz** [comment] 2018-03-20 07:27
Duplicate of  https://github.com/fairecasoimeme/ZiGate/issues/29

**Comment by doudz** [comment] 2018-04-12 12:26
The code 0xA9 means 

> An APSDE-DATA.request with a destination
> addressing mode set to 0x03 failed due to no
> corresponding short address found in the
> address map table.


Using the IEEE address twice I got the code 0xAD

>  An APSDE-DATA.request requesting
> security has resulted in an error during the
> corresponding security processing.

is it normal ? (I tried on a Xiaomi aqara switch http://zigate.fr/xiaomi-bouton-switch-aqara-clusters/ )

**Closed** 2019-01-10 18:12 UTC
